export const STR = {
  title: "2084 Static Wave - LottoMind",
  shortTitle: "2084 STATIC WAVE",
  presenter: "LOTTOMIND PRESENTS",
  runReady: "Signal armed",
  running: "Sector live",
  paused: "Signal paused",
  gameOver: "Signal lost",
  victory: "Static cleared",
  start: "Press start",
  startButton: "Start Sector 1",
  resume: "Resume signal",
  restart: "Restart",
  selectPilots: "Select pilots",
  mute: "Mute",
  unmute: "Sound",
  soundOn: "Sound On",
  soundOff: "Sound Off",
  score: "Score",
  level: "Sector",
  lives: "Lives",
  bombs: "Bombs",
  multiplier: "x",
  objective: "Static",
  best: "Archive",
  cleared: "Cleared",
  survived: "Survived",
  finalScore: "Final score",
  topScores: "Top 5 Scores",
  scoreArchive: "Local archive",
  scoreSaved: "saved",
  noScores: "No saved runs yet",
  scoreLegacy: "Best archive",
  overlayReady: "2084 Static Wave portal armed. Select pilots, start Sector 1, and break the static wells.",
  overlayPaused: "The signal is holding.",
  overlayGameOver: "The static archive kept that run.",
  overlayVictory: "The last signal well broke open.",
  controlsHint: "Gameplay controls: move with WASD or arrows. Fire with mouse, touch, IJKL, or keypad. Bomb with Space. Pause with P or Esc.",
  loading: "Loading assets",
  audioBlocked: "Tap start to arm sound",
  devLabel: "dev",
  bombButton: "Bomb",
  pauseButton: "Pause",
  muteButton: "Toggle sound",
  players: "Players",
  playerChip: "Pilots",
  playerOption1: "1P",
  playerOption2: "2P",
  playerOption3: "3P",
  playerOption4: "4P",
  forgeTitle: "Number Forge",
  forgeStartupNote: "Entertainment-only signal numbers",
  forgeRunNote: "updates on shards, wells, and clears",
  forgePickupNote: "shard tuned",
  forgeWellNote: "well cracked",
  forgeClearNote: "sector sealed",
  forgeStartNote: "run seed armed",
  forgeClose: "Hide Number Forge",
  forgeShow: "Show Number Forge",
  forgeToggle: "Forge"
};
