export const STR = {
  title: "2084 Static WAV - LottoMind",
  shortTitle: "2084 STATIC WAV",
  presenter: "LOTTOMIND PRESENTS",
  runReady: "Signal armed",
  running: "Sector live",
  paused: "Signal paused",
  gameOver: "Signal lost",
  victory: "Static cleared",
  start: "Press start",
  resume: "Resume signal",
  restart: "Restart",
  selectPilots: "Select pilots",
  mute: "Mute",
  unmute: "Sound",
  soundOn: "Sound On",
  soundOff: "Sound Off",
  score: "Score",
  level: "Sector",
  lives: "Lives",
  bombs: "Bombs",
  multiplier: "x",
  objective: "Static",
  best: "Archive",
  cleared: "Cleared",
  survived: "Survived",
  finalScore: "Final score",
  overlayReady: "LottoMind presents: enter the signal, survive the grid.",
  overlayPaused: "The signal is holding.",
  overlayGameOver: "The static archive kept that run.",
  overlayVictory: "The last signal well broke open.",
  loading: "Loading assets",
  audioBlocked: "Tap start to arm sound",
  devLabel: "dev",
  bombButton: "Bomb",
  pauseButton: "Pause",
  muteButton: "Toggle sound",
  players: "Players",
  playerChip: "Pilots",
  playerOption1: "1P",
  playerOption2: "2P",
  playerOption3: "3P",
  playerOption4: "4P",
  forgeTitle: "Number Forge",
  forgeStartupNote: "Entertainment-only signal numbers",
  forgeRunNote: "updates on shards, wells, and clears",
  forgePickupNote: "shard tuned",
  forgeWellNote: "well cracked",
  forgeClearNote: "sector sealed",
  forgeStartNote: "run seed armed",
  forgeClose: "Hide Number Forge"
};
