// Generated by tools/apply_brand.py. Do not edit.
#pragma once
namespace StaticWarsBrand {
inline constexpr const char* ProjectName = "2084 Static WAV";
inline constexpr const char* ProjectSlug = "2084-static-wav";
inline constexpr const char* PresentedBy = "LottoMind";
inline constexpr const char* Tagline = "Enter the signal. Survive the grid.";
inline constexpr const char* StartPrompt = "PRESS START";
inline constexpr const char* GameOver = "SIGNAL LOST";
inline constexpr const char* HighScores = "STATIC ARCHIVE";
inline constexpr const char* LicenseMenu = "LICENSE & NOTICES";
inline constexpr const char* ColorBackground = "#05070D";
inline constexpr const char* ColorGold = "#D4AF37";
inline constexpr const char* ColorCyan = "#29F7FF";
inline constexpr const char* ColorViolet = "#8E44FF";
inline constexpr const char* ColorMagenta = "#FF2DAA";
}
