import type { NewsSourceConfig } from "../types/news";

export const NEWS_SOURCES: NewsSourceConfig[] = [
  {
    id: "newsdata-latest",
    name: "NewsData Latest",
    url: "https://newsdata.io/api/1/latest?language=en&removeduplicate=1&q=lottery",
    type: "json",
    categories: ["Lottery News", "Jackpot Watch", "UFO / UAP", "The Unexplained", "Space Mystery"],
    credibilityLabel: "Established News",
    enabled: Boolean(process.env.NEWSDATA_API_KEY?.trim()),
    priority: 88,
    isOfficialSource: false,
    isFreeToRead: true,
  },
  {
    id: "newsdata-horoscopes",
    name: "NewsData Horoscopes",
    url: "https://newsdata.io/api/1/latest?language=en&removeduplicate=1&q=horoscope",
    type: "json",
    categories: ["Horoscopes"],
    credibilityLabel: "Entertainment",
    enabled: Boolean(process.env.NEWSDATA_API_KEY?.trim()),
    priority: 36,
    isOfficialSource: false,
    isFreeToRead: true,
  },
  {
    id: "astrologyapi-daily",
    name: "AstrologyAPI Daily Horoscopes",
    url: "https://json.astrologyapi.com/v1/sun_sign_prediction/daily/aries",
    type: "json",
    categories: ["Horoscopes"],
    credibilityLabel: "Entertainment",
    enabled: Boolean(process.env.ASTROLOGYAPI_ACCESS_TOKEN?.trim()),
    priority: 38,
    isOfficialSource: false,
    isFreeToRead: true,
  },
  {
    id: "michigan-lottery-connect",
    name: "Michigan Lottery Connect",
    url: "https://milotteryconnect.com/feed/",
    type: "rss",
    categories: ["Lottery News", "Lottery Winners", "Jackpot Watch", "Powerball / Mega Millions", "Pick 3 / Pick 4", "State Lottery", "Ticket Safety"],
    credibilityLabel: "Official",
    enabled: true,
    priority: 100,
    isOfficialSource: true,
    isFreeToRead: true,
  },
  {
    id: "texas-lottery-results",
    name: "Texas Lottery",
    url: "https://www.texaslottery.com/export/sites/lottery/rss/tlc_latest.xml",
    type: "rss",
    categories: ["Lottery News", "Jackpot Watch", "Powerball / Mega Millions", "Pick 3 / Pick 4", "State Lottery"],
    credibilityLabel: "Official",
    enabled: true,
    priority: 98,
    isOfficialSource: true,
    isFreeToRead: true,
  },
  {
    id: "powerball-news",
    name: "Powerball",
    url: "https://www.powerball.com/latest-news",
    type: "html",
    categories: ["Lottery News", "Lottery Winners", "Jackpot Watch", "Powerball / Mega Millions"],
    credibilityLabel: "Official",
    enabled: true,
    priority: 96,
    isOfficialSource: true,
    isFreeToRead: true,
  },
  {
    id: "mega-millions-history",
    name: "Mega Millions",
    url: "https://www.megamillions.com/About/Jackpot-History.aspx",
    type: "html",
    categories: ["Lottery Winners", "Jackpot Watch", "Powerball / Mega Millions"],
    credibilityLabel: "Official",
    enabled: true,
    priority: 94,
    isOfficialSource: true,
    isFreeToRead: true,
  },
  {
    id: "nasa-news-releases",
    name: "NASA",
    url: "https://www.nasa.gov/news-release/feed/",
    type: "rss",
    categories: ["Space Mystery", "The Unexplained"],
    credibilityLabel: "Scientific Source",
    enabled: true,
    priority: 92,
    isOfficialSource: true,
    isFreeToRead: true,
  },
  {
    id: "jpl-news",
    name: "NASA Jet Propulsion Laboratory",
    url: "https://www.jpl.nasa.gov/feeds/news/",
    type: "rss",
    categories: ["Space Mystery", "The Unexplained"],
    credibilityLabel: "Scientific Source",
    enabled: true,
    priority: 90,
    isOfficialSource: true,
    isFreeToRead: true,
  },
  {
    id: "aaro-uap-reports",
    name: "All-domain Anomaly Resolution Office",
    url: "https://www.aaro.mil/Next-AARO-Home-redesign/Next-Parent/Next-UAP-Report-Documents/",
    type: "html",
    categories: ["Official UAP", "UFO / UAP"],
    credibilityLabel: "Official",
    enabled: true,
    priority: 100,
    isOfficialSource: true,
    isFreeToRead: true,
  },
  {
    id: "aaro-trends",
    name: "AARO Reporting Trends",
    url: "https://www.aaro.mil/UAP-Cases/UAP-Reporting-Trends/",
    type: "html",
    categories: ["Official UAP", "UFO / UAP"],
    credibilityLabel: "Official",
    enabled: true,
    priority: 99,
    isOfficialSource: true,
    isFreeToRead: true,
  },
  {
    id: "numerology-specialist",
    name: "Numerology Specialist Feed",
    url: "https://numerologist.com/feed/",
    type: "rss",
    categories: ["Numerology"],
    credibilityLabel: "Entertainment",
    enabled: false,
    priority: 30,
    isOfficialSource: false,
    isFreeToRead: true,
  },
  {
    id: "horoscope-entertainment",
    name: "Horoscope Entertainment Feed",
    url: "https://www.horoscope.com/us/editorial/rss.aspx",
    type: "rss",
    categories: ["Horoscopes"],
    credibilityLabel: "Entertainment",
    enabled: false,
    priority: 25,
    isOfficialSource: false,
    isFreeToRead: true,
  },
];

export const ENABLED_NEWS_SOURCES = NEWS_SOURCES.filter((source) => source.enabled).sort(
  (left, right) => right.priority - left.priority,
);
