export const PACK_ROOT = "assets/GOTHTECHNOLOGY_EXPANDED_SPRITE_PACK_V2";
export const LOCAL_ROOT = "assets";

export const ASSET_URLS = {
  manifest: `${PACK_ROOT}/manifests/GOTHTECHNOLOGY_expanded_motion_manifest.json`,
  logo: `${LOCAL_ROOT}/user-title/lottomind-live-logo.png`,
  titleBackdrop: `${LOCAL_ROOT}/user-title/gothtechnology-cover-start-bg.png`,
  background: `${LOCAL_ROOT}/user-stage/forest-fight-background.jpg`,
  farTrees: `${PACK_ROOT}/backgrounds/GOTHTECHNOLOGY_PARALLAX_FAR_TREES.png`,
  fog: `${PACK_ROOT}/backgrounds/GOTHTECHNOLOGY_FOG_OVERLAY_TRANSPARENT.png`,
  embers: `${PACK_ROOT}/backgrounds/GOTHTECHNOLOGY_EMBERS_OVERLAY_TRANSPARENT.png`,
  ground: `${LOCAL_ROOT}/user-ground/obsidian-rock-ground.png`,
  music: `${LOCAL_ROOT}/audio/lottomind-frequency.mp3`,
  fightMusic: `${LOCAL_ROOT}/audio/miracle-gold-reset.mp3`,
  effects: {
    hitSpark: `${PACK_ROOT}/effects/sheets/HIT_SPARK_GOLD_sheet.png`,
    blockShield: `${PACK_ROOT}/effects/sheets/BLOCK_SHIELD_BLUE_sheet.png`,
    dust: `${PACK_ROOT}/effects/sheets/DUST_RUN_TRAIL_sheet.png`,
    kalyxFireSlash: `${PACK_ROOT}/effects/sheets/KALYX_FIRE_SLASH_sheet.png`,
    kalyxShadowClaw: `${PACK_ROOT}/effects/sheets/KALYX_SHADOW_CLAW_PROJECTILE_sheet.png`,
    ezraBlueBurst: `${PACK_ROOT}/effects/sheets/EZRA_BLUE_MAGIC_BURST_sheet.png`,
    ezraOwlArc: `${PACK_ROOT}/effects/sheets/EZRA_OWL_ARC_PROJECTILE_sheet.png`,
    emberOverlay: `${PACK_ROOT}/effects/sheets/EMBER_OVERLAY_sheet.png`,
    smoke: `${PACK_ROOT}/effects/sheets/SMOKE_PUFF_sheet.png`
  },
  assists: {
    owl: `${LOCAL_ROOT}/user-assists/ezra-owl-dive-clean.png`,
    raven: `${LOCAL_ROOT}/user-assists/kalyx-shadow-raven-clean.png`,
    nocturna: `${LOCAL_ROOT}/user-assists/nocturna-wraith-clean.png`
  },
  dossiers: {
    vespera: `${LOCAL_ROOT}/user-sheets/vespera-sheet.png`,
    nocturna: `${LOCAL_ROOT}/user-sheets/nocturna-sheet.png`,
    malach: `${LOCAL_ROOT}/user-sheets/malach-sheet.png`,
    morvane: `${LOCAL_ROOT}/user-sheets/morvane-sheet.png`,
    owl: `${LOCAL_ROOT}/user-sheets/owl-flight-sheet.png`,
    raven: `${LOCAL_ROOT}/user-sheets/shadow-raven-sheet.png`,
    wraith: `${LOCAL_ROOT}/user-sheets/wraith-flight-sheet.png`,
    bats: `${LOCAL_ROOT}/user-sheets/bat-swarm-sheet.png`,
    effects: `${LOCAL_ROOT}/user-sheets/flying-effects-sheet.png`
  }
};

export const SPRITE_OVERRIDES = {
  KALYX: {
    image: `${LOCAL_ROOT}/generated-sprites/kalyx-gpt2-motion-atlas.png`,
    frameWidth: 384,
    frameHeight: 384,
    frameDuration: 54,
    sourceFacing: 1,
    motions: {
      IDLE: [0],
      READY_STANCE: [1, 0],
      WALK_FORWARD: [0, 2, 0, 2],
      WALK_BACK: [2, 0, 2, 0],
      RUN_FORWARD: [2, 5, 2, 6],
      RUN_BACK: [2, 0, 2, 0],
      DASH_FORWARD: [2, 6, 5],
      DASH_BACK: [2, 0, 1],
      JUMP_START: [2],
      JUMP_RISE: [6],
      JUMP_PEAK: [6],
      JUMP_FALL: [6],
      LANDING: [3, 0],
      BLOCK_HIGH: [1],
      BLOCK_LOW: [1],
      CROUCH_IDLE: [3],
      CROUCH_WALK: [3, 4],
      CROUCH_ATTACK: [3, 4, 4, 3],
      LIGHT_PUNCH: [1, 5, 5, 1],
      HEAVY_PUNCH: [1, 5, 6, 1],
      LIGHT_KICK: [6, 6],
      HEAVY_KICK: [7, 7],
      AIR_ATTACK: [7, 7],
      THROW_GRAB: [1, 10, 10],
      THROW_FINISH: [10, 4, 1],
      COMBO_1: [1, 5, 6],
      COMBO_2: [6, 7, 10],
      SPECIAL_START: [4, 10],
      SPECIAL_PROJECTILE: [10, 10],
      SPECIAL_RECOVER: [1],
      SUPER_CHARGE: [4, 10],
      SUPER_RELEASE: [9, 10],
      HURT_LIGHT: [1],
      HURT_HEAVY: [1],
      KNOCKDOWN: [3],
      GET_UP: [3, 1, 0],
      TAUNT: [1, 0],
      VICTORY: [0, 1],
      DEFEAT: [3]
    }
  },
  MASTER_EZRA: {
    image: `${LOCAL_ROOT}/generated-sprites/ezra-stable-action-atlas.png`,
    frameWidth: 384,
    frameHeight: 384,
    frameDuration: 38,
    sourceFacing: 1,
    motions: {
      IDLE: [0],
      READY_STANCE: [1, 0],
      WALK_FORWARD: [2, 3, 4, 5],
      WALK_BACK: [5, 4, 3, 2],
      RUN_FORWARD: [2, 4, 5],
      RUN_BACK: [5, 4, 2],
      DASH_FORWARD: [4, 5],
      DASH_BACK: [5, 4],
      JUMP_START: [2],
      JUMP_RISE: [13],
      JUMP_PEAK: [12],
      JUMP_FALL: [13],
      LANDING: [6, 0],
      BLOCK_HIGH: [1],
      BLOCK_LOW: [6],
      CROUCH_IDLE: [6],
      CROUCH_WALK: [6, 7],
      CROUCH_ATTACK: [6, 7, 7, 6],
      LIGHT_PUNCH: [8, 9, 8],
      HEAVY_PUNCH: [8, 10, 11, 10],
      LIGHT_KICK: [12, 12],
      HEAVY_KICK: [12, 12],
      AIR_ATTACK: [12, 12],
      THROW_GRAB: [15, 15],
      THROW_FINISH: [15, 7, 0],
      COMBO_1: [8, 9, 12],
      COMBO_2: [10, 11, 12],
      SPECIAL_START: [11, 14],
      SPECIAL_PROJECTILE: [14, 14],
      SPECIAL_RECOVER: [11, 0],
      SUPER_CHARGE: [11, 14],
      SUPER_RELEASE: [14, 14],
      HURT_LIGHT: [1],
      HURT_HEAVY: [1],
      KNOCKDOWN: [16, 17],
      GET_UP: [17, 6, 0],
      TAUNT: [0, 1],
      VICTORY: [0, 1],
      DEFEAT: [17]
    }
  }
};

export const FIGHTERS = {
  KALYX: {
    id: "KALYX",
    name: "KALYX",
    title: "Shadow Rushdown",
    manifestKey: "KALYX",
    spriteFacing: 1,
    palette: "#f0a23b",
    accent: "#ffcf67",
    scale: 1.56,
    stableScale: 1.56,
    spriteFilter: "blur(0.16px) contrast(1.08) saturate(0.9)",
    stageMargin: 196,
    speed: 430,
    runSpeed: 720,
    dashSpeed: 1200,
    jumpVelocity: -1005,
    motionTimeScale: 1.48,
    feel: {
      attackStartupScale: 0.58,
      attackRecoveryScale: 0.48,
      attackActiveScale: 0.9,
      inputBuffer: 0.18,
      groundAccel: 4800,
      groundDecel: 4200,
      airAccel: 1500,
      dashBrake: 2100,
      landingLag: 0.012
    },
    maxHealth: 1000,
    attackOverrides: {
      lightPunch: {
        motion: "LIGHT_PUNCH",
        damage: 44,
        chip: 4,
        stun: 0.2,
        blockstun: 0.16,
        startup: 0.07,
        active: [0.07, 0.2],
        recovery: 0.16,
        reach: 105,
        width: 92,
        height: 58,
        y: -132,
        knockback: 165,
        level: "high"
      },
      heavyPunch: {
        motion: "HEAVY_PUNCH",
        damage: 88,
        chip: 8,
        stun: 0.33,
        blockstun: 0.24,
        startup: 0.13,
        active: [0.13, 0.32],
        recovery: 0.27,
        reach: 136,
        width: 126,
        height: 72,
        y: -134,
        knockback: 275,
        level: "high"
      },
      lightKick: {
        motion: "LIGHT_KICK",
        damage: 58,
        chip: 5,
        stun: 0.24,
        blockstun: 0.18,
        startup: 0.11,
        active: [0.11, 0.28],
        recovery: 0.22,
        reach: 108,
        width: 94,
        height: 64,
        y: -130,
        knockback: 215,
        level: "mid"
      },
      heavyKick: {
        motion: "HEAVY_KICK",
        damage: 104,
        chip: 9,
        stun: 0.37,
        blockstun: 0.27,
        startup: 0.14,
        active: [0.14, 0.38],
        recovery: 0.3,
        reach: 150,
        width: 138,
        height: 88,
        y: -152,
        knockback: 330,
        level: "high"
      },
      crouchAttack: {
        motion: "CROUCH_ATTACK",
        damage: 58,
        chip: 5,
        stun: 0.25,
        blockstun: 0.2,
        startup: 0.09,
        active: [0.09, 0.28],
        recovery: 0.2,
        reach: 126,
        width: 118,
        height: 50,
        y: -68,
        knockback: 190,
        level: "low"
      },
      airAttack: {
        motion: "AIR_ATTACK",
        damage: 82,
        chip: 5,
        stun: 0.32,
        blockstun: 0.24,
        startup: 0.08,
        active: [0.08, 0.36],
        recovery: 0.17,
        reach: 130,
        width: 134,
        height: 104,
        y: -148,
        knockback: 250,
        level: "high"
      }
    },
    assistNames: ["SHADOW RAVEN", "NOCTURNA WRAITH"],
    superName: "Shadow Roar",
    specialName: "Fire Slash"
  },
  MASTER_EZRA: {
    id: "MASTER_EZRA",
    name: "MASTER EZRA",
    title: "Blue Control",
    manifestKey: "MASTER_EZRA",
    spriteFacing: 1,
    palette: "#8bd4ff",
    accent: "#d8aa45",
    scale: 1.24,
    stableScale: 1.24,
    spriteFilter: "contrast(1.08) saturate(0.94)",
    speed: 410,
    runSpeed: 670,
    dashSpeed: 1150,
    jumpVelocity: -995,
    motionTimeScale: 1.46,
    feel: {
      attackStartupScale: 0.6,
      attackRecoveryScale: 0.5,
      attackActiveScale: 0.9,
      inputBuffer: 0.18,
      groundAccel: 4600,
      groundDecel: 4000,
      airAccel: 1450,
      dashBrake: 2000,
      landingLag: 0.012
    },
    maxHealth: 1060,
    attackOverrides: {
      lightKick: {
        motion: "LIGHT_KICK",
        damage: 58,
        chip: 5,
        stun: 0.26,
        blockstun: 0.2,
        startup: 0.1,
        active: [0.1, 0.32],
        recovery: 0.22,
        reach: 138,
        width: 136,
        height: 82,
        y: -116,
        knockback: 210,
        level: "mid"
      },
      heavyKick: {
        motion: "HEAVY_KICK",
        damage: 104,
        chip: 10,
        stun: 0.38,
        blockstun: 0.28,
        startup: 0.16,
        active: [0.16, 0.42],
        recovery: 0.34,
        reach: 164,
        width: 154,
        height: 88,
        y: -118,
        knockback: 330,
        level: "mid"
      },
      airAttack: {
        motion: "AIR_ATTACK",
        damage: 82,
        chip: 5,
        stun: 0.32,
        blockstun: 0.24,
        startup: 0.09,
        active: [0.09, 0.38],
        recovery: 0.18,
        reach: 134,
        width: 140,
        height: 102,
        y: -138,
        knockback: 250,
        level: "high"
      }
    },
    motionRemap: {
      RUN_FORWARD: "WALK_FORWARD",
      RUN_BACK: "WALK_BACK",
      DASH_FORWARD: "WALK_FORWARD",
      DASH_BACK: "WALK_BACK"
    },
    assistNames: ["OWL COMPANION", "ARCANE GUARD"],
    superName: "Sky Judgment",
    specialName: "Blue Magic"
  }
};
